spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5433}/${DB_NAME:auth_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true

#jwt:
#  secret: "mySuperSecureSecretKeyThatMustBeVeryLong12345678"
#  expiration: 86400000

jwt:
  secret: ${jwt.secret}
  expiration: ${jwt.expiration}